import { isValidElement } from 'react'

/**
 * A line lifted from the paper, marked up like a highlighter pass.
 *
 * `from` is the locator -- page, section, figure, equation number -- so a quote
 * can always be traced back. Keep excerpts short; this is for the sentence being
 * reacted to, not for reproducing the paper.
 *
 * With `src`, it renders an actual crop of the PDF with the line highlighted --
 * generated by `scripts/paper-clip.py`, which caps a clip at a handful of lines.
 * The children are still required in that case: they become the alt text, so the
 * quote is readable to a screen reader and findable by search even though the
 * visible version is a raster image.
 */
/** Flatten children to plain text for the `alt` attribute. MDX wraps block
 *  children in a <p>, so the quote is never a bare string here. */
function text(node: React.ReactNode): string
{
  if (node === null || node === undefined || typeof node === 'boolean') return ''
  if (typeof node === 'string' || typeof node === 'number') return String(node)
  if (Array.isArray(node)) return node.map(text).join('')
  if (isValidElement(node))
  {
    return text((node.props as { children?: React.ReactNode }).children)
  }
  return ''
}

export default function Excerpt({
  children,
  from,
  src,
}: {
  children: React.ReactNode
  from?: string
  src?: string
})
{
  if (src)
  {
    return (
      <figure className="not-prose my-6">
        {/* The crop is white paper. Framed rather than inverted: a scan reads as
            a scan, and inverting would turn the amber highlight blue. Dimmed a
            touch in dark mode so it is not a slab of glare. */}
        <div className="overflow-x-auto rounded-md border border-gray-200 dark:border-gray-700">
          <img
            src={src}
            alt={text(children).trim()}
            className="block w-full min-w-[360px] bg-white dark:opacity-90"
          />
        </div>
        <figcaption className="mt-1.5 text-[11px] uppercase tracking-wider text-gray-400">
          {from ?? 'from the paper'}
        </figcaption>
      </figure>
    )
  }

  return (
    <figure className="not-prose my-6">
      <blockquote className="relative border-l-[3px] border-amber-400 pl-4 pr-3 py-2 bg-amber-50/70 dark:bg-amber-500/10 rounded-r-md">
        <p className="text-[0.95rem] leading-relaxed text-gray-800 dark:text-gray-200 italic">
          {children}
        </p>
      </blockquote>
      {from && (
        <figcaption className="mt-1.5 pl-4 text-[11px] uppercase tracking-wider text-gray-400">
          {from}
        </figcaption>
      )}
    </figure>
  )
}
